// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'artist.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Artist _$ArtistFromJson(Map<String, dynamic> json) => Artist(
      id: json['idArtist'] as String?,
      name: json['strArtist'] as String?,
      alternativeName: json['strArtistAlternate'] as String?,
      label: json['strLabel'] as String?,
      labelId: json['idLabel'] as String?,
      formedYear: json['intFormedYear'] as String?,
      bornYear: json['intBornYear'] as String?,
      diedYear: json['intDiedYear'] as String?,
      disbanded: json['strDisbanded'] as String?,
      style: json['strStyle'] as String?,
      genre: json['strGenre'] as String?,
      mood: json['strMood'] as String?,
      website: json['strWebsite'] as String?,
      facebook: json['strFacebook'] as String?,
      twitter: json['strTwitter'] as String?,
      biography: json['strBiographyEN'] as String?,
      gender: json['strGender'] as String?,
      members: json['intMembers'] as String?,
      country: json['strCountry'] as String?,
      countryCode: json['strCountryCode'] as String?,
      thumb: json['strArtistThumb'] as String?,
      logo: json['strArtistLogo'] as String?,
      cutout: json['strArtistCutout'] as String?,
      clearart: json['strArtistClearart'] as String?,
      wideThumb: json['strArtistWideThumb'] as String?,
      fanart: json['strArtistFanart'] as String?,
      fanart2: json['strArtistFanart2'] as String?,
      fanart3: json['strArtistFanart3'] as String?,
      fanart4: json['strArtistFanart4'] as String?,
      banner: json['strArtistBanner'] as String?,
      musicBrainzId: json['strMusicBrainzID'] as String?,
      isniCode: json['strISNIcode'] as String?,
      lastFmChart: json['strLastFMChart'] as String?,
      locked: json['strLocked'] as String?,
    );

Map<String, dynamic> _$ArtistToJson(Artist instance) => <String, dynamic>{
      'idArtist': instance.id,
      'strArtist': instance.name,
      'strArtistAlternate': instance.alternativeName,
      'strLabel': instance.label,
      'idLabel': instance.labelId,
      'intFormedYear': instance.formedYear,
      'intBornYear': instance.bornYear,
      'intDiedYear': instance.diedYear,
      'strDisbanded': instance.disbanded,
      'strStyle': instance.style,
      'strGenre': instance.genre,
      'strMood': instance.mood,
      'strWebsite': instance.website,
      'strFacebook': instance.facebook,
      'strTwitter': instance.twitter,
      'strBiographyEN': instance.biography,
      'strGender': instance.gender,
      'intMembers': instance.members,
      'strCountry': instance.country,
      'strCountryCode': instance.countryCode,
      'strArtistThumb': instance.thumb,
      'strArtistLogo': instance.logo,
      'strArtistCutout': instance.cutout,
      'strArtistClearart': instance.clearart,
      'strArtistWideThumb': instance.wideThumb,
      'strArtistFanart': instance.fanart,
      'strArtistFanart2': instance.fanart2,
      'strArtistFanart3': instance.fanart3,
      'strArtistFanart4': instance.fanart4,
      'strArtistBanner': instance.banner,
      'strMusicBrainzID': instance.musicBrainzId,
      'strISNIcode': instance.isniCode,
      'strLastFMChart': instance.lastFmChart,
      'strLocked': instance.locked,
    };
